package com.vista.security.core;

import burp.IExtensionHelpers;
import burp.IHttpRequestResponse;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Generates security assessment reports in various formats.
 */
public final class ReportGenerator {
    
    private ReportGenerator() {
        // Utility class - prevent instantiation
    }
    
    /**
     * Generate a Markdown report of all requests, analysis, and findings.
     */
    public static String generateMarkdownReport(
            IExtensionHelpers helpers,
            List<IHttpRequestResponse> requests,
            Map<IHttpRequestResponse, StringBuilder> analysisHistory,
            Map<IHttpRequestResponse, List<String>> findings) {
        
        StringBuilder report = new StringBuilder();
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
        
        // Header
        report.append("# VISTA Security Assessment Report\n\n");
        report.append("**Generated:** ").append(timestamp).append("\n\n");
        report.append("**Total Requests Analyzed:** ").append(requests.size()).append("\n\n");
        
        // Executive Summary
        report.append("## Executive Summary\n\n");
        Map<String, Integer> severityCounts = countFindingsBySeverity(findings);
        int totalFindings = severityCounts.values().stream().mapToInt(Integer::intValue).sum();
        
        report.append("| Severity | Count |\n");
        report.append("|----------|-------|\n");
        for (Map.Entry<String, Integer> entry : severityCounts.entrySet()) {
            if (entry.getValue() > 0) {
                report.append("| ").append(entry.getKey()).append(" | ").append(entry.getValue()).append(" |\n");
            }
        }
        report.append("\n**Total Findings:** ").append(totalFindings).append("\n\n");
        
        // Detailed Findings
        report.append("## Detailed Findings\n\n");
        
        int requestNumber = 1;
        for (IHttpRequestResponse request : requests) {
            String requestText = HttpMessageParser.requestToText(helpers, request.getRequest());
            String[] lines = requestText.split("\\r?\\n");
            String firstLine = lines.length > 0 ? lines[0] : "(unknown)";
            String host = HttpMessageParser.extractHeader(requestText, "Host");
            host = host != null ? host : "";
            
            report.append("### ").append(requestNumber++).append(". ")
                  .append(host).append(" - ").append(truncate(firstLine, 60)).append("\n\n");
            
            // Findings for this request
            List<String> requestFindings = findings.get(request);
            if (requestFindings != null && !requestFindings.isEmpty()) {
                report.append("#### Findings\n\n");
                for (String finding : requestFindings) {
                    report.append("- ").append(finding).append("\n");
                }
                report.append("\n");
            }
            
            // Analysis history
            StringBuilder analysis = analysisHistory.get(request);
            if (analysis != null && analysis.length() > 0) {
                report.append("#### Analysis Notes\n\n");
                report.append("```\n");
                String analysisText = analysis.toString();
                if (analysisText.length() > 5000) {
                    analysisText = analysisText.substring(0, 5000) + "\n...[truncated]...";
                }
                report.append(analysisText);
                report.append("```\n\n");
            }
            
            // Request details (collapsible)
            report.append("<details>\n<summary>Request Details</summary>\n\n");
            report.append("```http\n");
            report.append(truncate(requestText, 2000));
            report.append("\n```\n\n");
            report.append("</details>\n\n");
            
            report.append("---\n\n");
        }
        
        // Appendix
        report.append("## Appendix\n\n");
        report.append("This report was generated by **VISTA** (Vulnerability Insight & Strategic Test Assistant) ");
        report.append("Burp Suite Extension.\n\n");
        report.append("**Disclaimer:** This report is for authorized security testing purposes only. ");
        report.append("All findings should be verified manually before reporting.\n");
        
        return report.toString();
    }
    
    /**
     * Generate a simple text summary.
     */
    public static String generateTextSummary(
            IExtensionHelpers helpers,
            List<IHttpRequestResponse> requests,
            Map<IHttpRequestResponse, List<String>> findings) {
        
        StringBuilder sb = new StringBuilder();
        sb.append("VISTA Assessment Summary\n");
        sb.append("========================\n\n");
        sb.append("Requests Analyzed: ").append(requests.size()).append("\n");
        
        int totalFindings = 0;
        for (List<String> f : findings.values()) {
            if (f != null) totalFindings += f.size();
        }
        sb.append("Total Findings: ").append(totalFindings).append("\n\n");
        
        if (totalFindings > 0) {
            sb.append("All Findings:\n");
            for (Map.Entry<IHttpRequestResponse, List<String>> entry : findings.entrySet()) {
                if (entry.getValue() != null && !entry.getValue().isEmpty()) {
                    for (String finding : entry.getValue()) {
                        sb.append("  - ").append(finding).append("\n");
                    }
                }
            }
        }
        
        return sb.toString();
    }
    
    private static Map<String, Integer> countFindingsBySeverity(Map<IHttpRequestResponse, List<String>> findings) {
        Map<String, Integer> counts = new LinkedHashMap<>();
        counts.put("Critical", 0);
        counts.put("High", 0);
        counts.put("Medium", 0);
        counts.put("Low", 0);
        counts.put("Info", 0);
        
        for (List<String> requestFindings : findings.values()) {
            if (requestFindings != null) {
                for (String finding : requestFindings) {
                    for (String severity : counts.keySet()) {
                        if (finding.contains("[" + severity + "]")) {
                            counts.put(severity, counts.get(severity) + 1);
                            break;
                        }
                    }
                }
            }
        }
        
        return counts;
    }
    
    private static String truncate(String s, int maxLength) {
        if (s == null) return "";
        return s.length() > maxLength ? s.substring(0, maxLength) + "..." : s;
    }
}
